### ISSUE TITLE
Specify the python version

### ISSUE THREAD

**Issue by martin3398** [winny-/pre-commit-docker#1]
For me, this script is fixed Python < 3.10, but unfortunately I would like to use Python 3.11.

Is it possible to specify the python version. E. g., as docker tag or using a conda environment (since venv does not seem to be enough).

**Comment by winny-** [comment]
Hi there.  I have good news and bad news.  The bad news is this pre-commit image uses the system Python provided with Debian so it won't be possible to parameterize on the Python version.  The good news is debian bookworm has been stabilized, so I've [upgraded](https://gitlab.com/winny/pre-commit-docker/-/merge_requests/3) the docker image to Python 3.11 (provided by bookworm).  Hope this helps!
